### ISSUE TITLE
Hardcoded paths causing errors when trying to install package

### ISSUE THREAD

**Issue by doomlaser** [RageAgainstThePixel/com.openai.unity#13]
# Bug Report
When adding the package, errors are populated with hardcoded paths such as:
```
[Package Manager Window] Error adding package: https://github.com/RageAgainstThePixel/com.openai.unity.git#upm.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:356)
```

**Comment by StephenHodgson** [comment]
I created a quick project with the same setup. There's a dependency on [`com.utilities.rest`](https://github.com/RageAgainstThePixel/com.utilities.rest) that you're also missing:

```
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/RageAgainstThePixel/com.openai.unity.git#upm]:
  Package com.openai.unity@https://github.com/RageAgainstThePixel/com.openai.unity.git#upm has invalid dependencies or related test packages:
    com.utilities.rest (dependency): Package [com.utilities.rest@1.0.1] cannot be found [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

I encourage you to use the [OpenUPM installation method](https://github.com/RageAgainstThePixel/com.openai.unity#via-unity-package-manager-and-openupm) instead because it supports dependencies and versioning better.

**Comment by tomkail** [comment]
Can I suggest improving this import issue? We encountered exactly the same problem yesterday, and it's rather fiddly to fix. Unity's package management system isn't fantastic and it can be quite hard to understand what's wrong.
In our case, we encountered this when we tried to copy the code directly (since we wanted to modify it). 
I'm not too sure what to suggest, but it might be worth trying to set up with a new project and pretend you don't have a clue how UPM works :D

**Comment by StephenHodgson** [comment]
It's not really something we have control over. It's purely in the area of the unity of editor.

In my honest opinion you shouldn't be using the git URL method for installation since it doesn't handle versioning and dependencies as nicely as if you use the scoped registry.

> we tried to copy the code directly (since we wanted to modify it)

I would suggest forking, and then adding the package as a local reference in your working project instead. That way you can make changes and commit it back to git, then open a pull request with the changes you have in mind.
