### ISSUE TITLE
AudioTranscriptionRequest AudioClip Encoding Issues

### ISSUE THREAD

**Issue by MaZyGer** [RageAgainstThePixel/com.openai.unity#131]
# Bug Report

## Overview
using AudioTranscriptionRequest does not return the words I say. Tested in german and english. Both are giving me random lines.

For instance If I say "hallo" it response with "hää?" and in english as "huh?". I also used pre recorded wav files. It is same. Sometimes it also repeat words 3 - 10 times

**Comment by StephenHodgson** [comment]
Not sure this is a bug with my library specifically.

**Comment by StephenHodgson** [comment]
Have this endpoint for several clients, and have used it without problems. 

Double check your audio encoding and Open up a new post in my discord under troubleshooting.

**Comment by StephenHodgson** [comment]
I was digging through recent unit tests and found out that this may in fact be a bug.
I noticed in my unit tests there is a discrepancy in audio specifier vs path specifier:

### Test_1_Transcription_AudioClip (2.214s)

Warren Ibsen was the lead bunny tax in the printing and type setting industry. Warren Ibsen has been an industry standard bunny tax since the 1500s. For an unknown printer to download files and frame them to make a text testing body. It has survived nearly 5 centuries, but also removed into electronic type setting, remaining essentially unchanged. It was popularized in the 1950s with the release of winter sections containing Warren Ibsen passages, and more recently with desktop publishing software like August Pagemaker, including versions of Warren Ibsen.

### Test_1_Transcription_Path (2.470s)

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularized in the 1960s with the release of letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker, including versions of Lorem Ipsum.

I'll run some tests on the wav encoder and ensure it is not corrupting the audio clip somehow and also try a different encoding method.

**Comment by StephenHodgson** [comment]
Addressed in #132 

Please comment here again if this release does not fix your issue or reach out in discord.
